<?xml version="1.0" encoding="utf-8"?><Database Name="QL_MUABAN_TBDT" Class="QL_MBTBDTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=VIETSACLO-PC\SQLEXPRESS;Initial Catalog=QL_MUABAN_TBDT;User ID=sa" SettingsObjectName="DAL_BLL.Properties.Settings" SettingsPropertyName="QL_MUABAN_TBDTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CT_PHIEU_NHAP" Member="CT_PHIEU_NHAPs">
    <Type Name="CT_PHIEU_NHAP">
      <Column Name="MAPN" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SL_NHAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIANHAP" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="SanPham_CT_PHIEU_NHAP" Member="SanPham" ThisKey="MASP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
      <Association Name="PHIEU_NHAP_CT_PHIEU_NHAP" Member="PHIEU_NHAP" ThisKey="MAPN" OtherKey="MAPN" Type="PHIEU_NHAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSP" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Hinh" Type="System.String" DbType="NVarChar(700)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SL_TON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ISDELETE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SanPham_CT_PHIEU_NHAP" Member="CT_PHIEU_NHAPs" ThisKey="MaSP" OtherKey="MASP" Type="CT_PHIEU_NHAP" />
      <Association Name="SanPham_CTDonHang" Member="CTDonHangs" ThisKey="MaSP" OtherKey="MaSP" Type="CTDonHang" />
      <Association Name="LoaiSP_SanPham" Member="LoaiSP" ThisKey="MaLoai" OtherKey="MaLoai" Type="LoaiSP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTDonHang" Member="CTDonHangs">
    <Type Name="CTDonHang">
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Association Name="SanPham_CTDonHang" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
      <Association Name="DonHang_CTDonHang" Member="DonHang" ThisKey="MaDH" OtherKey="MaDH" Type="DonHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="MaDM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDM" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ISDELETE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DanhMuc_LoaiSP" Member="LoaiSPs" ThisKey="MaDM" OtherKey="MaDM" Type="LoaiSP" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrangGiaoHang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DonHang_CTDonHang" Member="CTDonHangs" ThisKey="MaDH" OtherKey="MaDH" Type="CTDonHang" />
      <Association Name="KhachHang_DonHang" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KhachHang_DonHang" Member="DonHangs" ThisKey="MaKH" OtherKey="MaKH" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiSP" Member="LoaiSPs">
    <Type Name="LoaiSP">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenLoaiSP" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ISDELETE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LoaiSP_SanPham" Member="SanPhams" ThisKey="MaLoai" OtherKey="MaLoai" Type="SanPham" />
      <Association Name="DanhMuc_LoaiSP" Member="DanhMuc" ThisKey="MaDM" OtherKey="MaDM" Type="DanhMuc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MANCC" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="NHACUNGCAP_PHIEU_NHAP" Member="PHIEU_NHAPs" ThisKey="MANCC" OtherKey="NHACC" Type="PHIEU_NHAP" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIENS" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PASS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TENNHANVIEN" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NHANVIEN_PHANNHANVIEN_VAONHOMQUYEN" Member="PHANNHANVIEN_VAONHOMQUYENs" ThisKey="USERNAME" OtherKey="USERNAME" Type="PHANNHANVIEN_VAONHOMQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.NHOMQUYENS" Member="NHOMQUYENs">
    <Type Name="NHOMQUYEN">
      <Column Name="MANHOM" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOM" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="NHOMQUYEN_PHANNHANVIEN_VAONHOMQUYEN" Member="PHANNHANVIEN_VAONHOMQUYENs" ThisKey="MANHOM" OtherKey="MANHOM" Type="PHANNHANVIEN_VAONHOMQUYEN" />
      <Association Name="NHOMQUYEN_PHANQUYEN" Member="PHANQUYENs" ThisKey="MANHOM" OtherKey="MANHOM" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.PHANNHANVIEN_VAONHOMQUYEN" Member="PHANNHANVIEN_VAONHOMQUYENs">
    <Type Name="PHANNHANVIEN_VAONHOMQUYEN">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOM" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="NHANVIEN_PHANNHANVIEN_VAONHOMQUYEN" Member="NHANVIEN" ThisKey="USERNAME" OtherKey="USERNAME" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="NHOMQUYEN_PHANNHANVIEN_VAONHOMQUYEN" Member="NHOMQUYEN" ThisKey="MANHOM" OtherKey="MANHOM" Type="NHOMQUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="MANHOM" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAQUYEN" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NHOMQUYEN_PHANQUYEN" Member="NHOMQUYEN" ThisKey="MANHOM" OtherKey="MANHOM" Type="NHOMQUYEN" IsForeignKey="true" />
      <Association Name="QUYEN_PHANQUYEN" Member="QUYEN" ThisKey="MAQUYEN" OtherKey="MAQUYEN" Type="QUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEU_NHAP" Member="PHIEU_NHAPs">
    <Type Name="PHIEU_NHAP">
      <Column Name="MAPN" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NHACC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="PHIEU_NHAP_CT_PHIEU_NHAP" Member="CT_PHIEU_NHAPs" ThisKey="MAPN" OtherKey="MAPN" Type="CT_PHIEU_NHAP" />
      <Association Name="NHACUNGCAP_PHIEU_NHAP" Member="NHACUNGCAP" ThisKey="NHACC" OtherKey="MANCC" Type="NHACUNGCAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUYENS" Member="QUYENs">
    <Type Name="QUYEN">
      <Column Name="MAQUYEN" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENQUYEN" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="QUYEN_PHANQUYEN" Member="PHANQUYENs" ThisKey="MAQUYEN" OtherKey="MAQUYEN" Type="PHANQUYEN" />
    </Type>
  </Table>
</Database>